version: "3.8"

services:
  web:
    build: .
    ports:
      - "8101:8101"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true
